### ISSUE TITLE
给甲种本的一些建议

### ISSUE THREAD

**Issue by A6669** [fanhongtao/ebooks#3]
首先非常感谢您能在自己业余闲暇，完成甲种本的LaTex化，我觉得这对于现代的中学生大有裨益。
同时提出几个意见
1. 可以先考虑出一个完整学科，如果数理化都出太困难，可以现考虑出完整的数学，包括初中和高中数学，现在已经有代数三册，还差立体几何，解析几何（Latex工作室的版本没有开源还需要付费），微积分初步和初中数学。
2. 对于课本中的图像可以先使用截图，而不是tikz绘图，当然如果图形很简单可以使用tikz直接绘制，这么做的原因是希望能够快速完成书籍，tikz绘图可以在之后的版本中逐渐改进。
3. 增加释出频率，不一定一整本写完才释出一次，只要有所改进，例如修改错别字，更改图片就可以释出，现在阁下只释出了两次，有些少了，可以考虑每三个月或半年释出一次。

**Comment by huguang1995** [comment]
我发现作者TEX源代码一直在提交和更新，其实如果可以的话。你可以自己下载TEX源代码之后，用TEX Live编译成PDF文件。

**Comment by Geno1024** [comment]
作者可以考虑搞一下 GitHub Actions，如果作者没空的话我或许可以试试搞一下

**Comment by 1183807453** [comment]
您好，您的邮件我已经收到。看到邮件后，我会尽快给您回复。                                                          胡广

**Comment by geezhu** [comment]
等着，这几天《algebra chapter 0》 latex化翻译完就来干

**Comment by huguang1995** [comment]
您好，您的邮件我已经收到。看到邮件后，我会尽快给您回复。                                                          胡广

**Comment by alextaoo** [comment]
请问能否分享完整编排的PDF版本？您这边代码版本很麻烦，非常感谢！

**Comment by geezhu** [comment]
> 版本

release里面有

**Comment by geezhu** [comment]
> 请问能否分享完整编排的PDF版本？您这边代码版本很麻烦，非常感谢！

release里面有 @alextaoo

**Comment by geezhu** [comment]
蹭个流量，发布了一个初步版本的《平面解析几何》以及《微积分初步》
 https://github.com/geezhu/Category-A-Textbook

**Comment by fanhongtao** [comment]
1. 初中的化数、物理、化学，已经完成，就差几何，马上会开工。
2. 其它版本，如果有人完成，我就在  readme 中加入链接。
3. 版本发布，是采取的完成一科发布一次。你也可以下载源码自行编译。

**Comment by huguang1995** [comment]
您好，您的邮件我已经收到。看到邮件后，我会尽快给您回复。                                                          胡广
