### ISSUE TITLE
和其他项目合作及其他建议

### ISSUE THREAD

**Issue by cute-omega** [fanhongtao/ebooks#7]
[这里](https://github.com/jamesfang8499/physics2)已经有人在弄物理甲种本第二册了，可以考虑合作

**Comment by cute-omega** [comment]
另外可以先放影印版，再弄电子版，毕竟有的用总比没得用好，我有一本中学级别的 代数方程与置换群，如果需要可以放上来

**Comment by geezhu** [comment]
哥们，你看下readme吧，作者已经贴出来了

**Comment by geezhu** [comment]
影印版到处都是，[教材](https://pan.quark.cn/s/d6e43ee688bc)

**Comment by fanhongtao** [comment]
物理，[james](https://github.com/jamesfang8499/) 早已经完成了。
