### ISSUE TITLE
一些提议

### ISSUE THREAD

**Issue by LegolasUndomiel** [fanhongtao/ebooks#8]
我家里有一套1992年10月第1版  1998年6月第6次印刷的初中《代数》和《几何》书籍，我与电子书做了比较，全书内容大体相似，只是在1992年的版本中，第一册多了一个章节，即92版第一册第一章，名为“代数初步知识”，用来衔接小学和初中数学知识，是否考虑加入电子书中？

**Comment by fanhongtao** [comment]
针对原教材的增补的内容，你可以考虑在现有代码的基础上，自己录入。
